const POS={you:[50,92],planner:[50,75],router:[50,60],qwen:[10,37],openai:[23,24],gemini:[38,37],claude:[50,12],deepseek:[62,37],grok:[77,24],mistral:[90,37],kimi:[30,8],perplexity:[70,8],reviewer:[50,46]};
const INFO={you:['YOU','Prompt'],planner:['PLANNER','Understands'],router:['ROUTER','Chooses team'],qwen:['QWEN','Code + reasoning'],openai:['OPENAI','General + coding'],gemini:['GEMINI','Research + design'],claude:['CLAUDE','Review + reasoning'],deepseek:['DEEPSEEK','Reasoning + code'],grok:['GROK','Critic'],mistral:['MISTRAL','Fast generalist'],kimi:['KIMI','Long context'],perplexity:['PERPLEXITY','Research'],reviewer:['REVIEWER','Independent validation']};
const FAMILY=['qwen','openai','gemini','claude','deepseek','grok','mistral','kimi','perplexity'];
const ROUTES={coding:['qwen','openai','claude'],research:['perplexity','gemini','claude'],automation:['openai','qwen','deepseek'],design:['gemini','claude','openai'],reasoning:['deepseek','openai','claude'],general:['openai','claude','gemini']};
const PREF={
 qwen:[/qwen3[ ._-]?8.*max/i,/qwen3[ ._-]?7.*max/i,/qwen.*coder/i,/qwen/i],
 openai:[/gpt[ ._-]?5[ ._-]?6.*sol/i,/gpt[ ._-]?5[ ._-]?6.*luna/i,/gpt[ ._-]?5[ ._-]?5/i,/gpt/i],
 gemini:[/gemini.*3[ ._-]?6.*flash/i,/gemini.*3[ ._-]?1.*pro/i,/gemini.*3/i,/gemini/i],
 claude:[/claude.*sonnet.*4[ ._-]?6/i,/claude.*opus.*5/i,/claude.*opus.*4[ ._-]?8/i,/claude/i],
 deepseek:[/deepseek.*v?4.*flash/i,/deepseek.*v?4.*pro/i,/deepseek/i],
 grok:[/grok.*4[ ._-]?6/i,/grok.*4[ ._-]?20/i,/grok/i],
 mistral:[/mistral.*medium.*3[ ._-]?5/i,/mistral.*small.*4/i,/mistral/i],
 kimi:[/kimi.*k2[ ._-]?7/i,/kimi.*k2[ ._-]?6/i,/kimi/i],
 perplexity:[/sonar.*pro/i,/perplexity/i,/sonar/i]
};
const PROVIDER={qwen:/qwen|alibaba/i,openai:/openai/i,gemini:/google|gemini/i,claude:/anthropic|claude/i,deepseek:/deepseek/i,grok:/xai|x\.ai|grok/i,mistral:/mistral/i,kimi:/moonshot|kimi/i,perplexity:/perplexity/i};
const $=id=>document.getElementById(id),edges=$('edges'),nodes=$('nodes'),stars=$('stars'),q=$('q'),go=$('go'),answer=$('answer'),workspace=$('workspace');
let models=[],busy=false,active=new Set(),selected=new Set(),activeEdges=new Set(),answered=false;
function classify(t){const s=t.toLowerCase();if(/\b(code|bug|fix|debug|refactor|python|javascript|typescript|abap|cds|sql|api|program|function)\b/.test(s))return'coding';if(/\b(research|find|discover|compare|analyse|analyze|latest|source|news|security|privacy|market|repo|github)\b/.test(s))return'research';if(/\b(workflow|automate|automation|schedule|monitor|alert|pipeline|action)\b/.test(s))return'automation';if(/\b(design|layout|ui|ux|website|visual|style|interface|screen)\b/.test(s))return'design';if(/\b(reason|logic|solve|why|trade.?off|decision|calculate|math)\b/.test(s))return'reasoning';return'general'}
function providerText(m){return `${m.provider||''} ${m.id||''} ${m.name||''}`}
function pick(f){const pool=models.filter(m=>PROVIDER[f].test(providerText(m)));for(const re of PREF[f]){const hit=pool.find(m=>re.test(`${m.name||''} ${m.id||''}`));if(hit)return hit}return pool[0]||null}
function modelName(m){return m?.name||m?.id||'unavailable'}
async function ensureModels(){if(models.length)return;models=await puter.ai.listModels();if(!Array.isArray(models)||!models.length)throw new Error('No AI models available')}
function draw(){edges.innerHTML='';const links=[['you','planner'],['planner','router'],...FAMILY.map(x=>['router',x]),...FAMILY.map(x=>[x,'reviewer']),['reviewer','you']];for(const [a,b] of links){const A=POS[a],B=POS[b],p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M ${A[0]} ${A[1]} C ${A[0]} ${(A[1]+B[1])/2}, ${B[0]} ${(A[1]+B[1])/2}, ${B[0]} ${B[1]}`);p.setAttribute('class','edge');p.dataset.e=`${a}:${b}`;edges.appendChild(p)}for(const [id,p] of Object.entries(POS)){const n=document.createElement('div');n.id=`n-${id}`;n.className=`node ${id==='you'?'you ':''}`;n.style.left=`${p[0]}%`;n.style.top=`${p[1]}%`;n.innerHTML=`<div class="halo"></div><div class="core"><span>${id==='you'?'◎':id==='reviewer'?'✓':'✦'}</span></div><strong>${INFO[id][0]}</strong><small>${INFO[id][1]}</small>`;nodes.appendChild(n)}render()}
function render(){document.querySelectorAll('.edge').forEach(e=>e.classList.toggle('on',activeEdges.has(e.dataset.e)));for(const id of Object.keys(POS)){const n=$(`n-${id}`);n.classList.toggle('active',active.has(id));n.classList.toggle('answered',answered&&id==='you');if(FAMILY.includes(id))n.classList.toggle('dim',selected.size>0&&!selected.has(id))}document.querySelector('.state').className=`state ${busy?'busy':answered?'done':''}`;$('stateText').textContent=busy?'WORKING':answered?'ANSWERED':'READY';go.disabled=busy||!q.value.trim()}
function star(a,b){const A=POS[a],B=POS[b],d=document.createElement('div');d.className='star';d.style.setProperty('--x1',`${A[0]}%`);d.style.setProperty('--y1',`${A[1]}%`);d.style.setProperty('--x2',`${B[0]}%`);d.style.setProperty('--y2',`${B[1]}%`);d.innerHTML='<span></span>';stars.appendChild(d);setTimeout(()=>d.remove(),800)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function travel(a,b,ms=360){active=new Set([b]);activeEdges=new Set([`${a}:${b}`]);star(a,b);render();await wait(ms)}
function role(kind){return kind==='coding'?'senior coding specialist':kind==='research'?'rigorous research analyst':kind==='automation'?'automation and reliability engineer':kind==='design'?'product and UI specialist':kind==='reasoning'?'careful analytical reasoner':'strong general problem solver'}
async function chat(model,question,kind){const r=await puter.ai.chat([{role:'system',content:`You are the ${role(kind)} in an AI team. Answer the user directly. Check assumptions and correctness. Be concise unless detail is necessary.`},{role:'user',content:question}],{model:model.id,normalize:true});const text=r?.message?.content;if(!text)throw new Error(`${modelName(model)} returned no answer`);return String(text).trim()}
async function callFamily(f,question,kind){const first=pick(f),fallbacks=['openai','gemini','claude','qwen','deepseek','mistral'].map(pick).filter(Boolean),seen=new Set();let last;for(const m of [first,...fallbacks]){if(!m||seen.has(m.id))continue;seen.add(m.id);try{return{family:f,model:m,text:await chat(m,question,kind)}}catch(e){last=e}}throw last||new Error(`${f} unavailable`)}
async function ask(){const question=q.value.trim();if(!question||busy)return;busy=true;answered=false;selected.clear();active.clear();activeEdges.clear();answer.classList.remove('open');workspace.classList.remove('open');render();try{if(!puter.auth.isSignedIn())await puter.auth.signIn({attempt_temp_user_creation:true});await ensureModels();const kind=classify(question),route=ROUTES[kind],workers=route.slice(0,2),reviewer=route[2];await travel('you','planner');await travel('planner','router');selected=new Set([...workers,reviewer]);active=new Set(workers);activeEdges=new Set(workers.map(x=>`router:${x}`));workers.forEach(x=>star('router',x));render();const results=await Promise.all(workers.map(x=>callFamily(x,question,kind)));results.forEach(r=>star(r.family,'reviewer'));active=new Set(['reviewer']);activeEdges=new Set(results.map(r=>`${r.family}:reviewer`));render();const reviewModel=pick(reviewer)||pick('claude')||pick('gemini')||pick('openai');if(!reviewModel)throw new Error('No reviewer model available');const synthesis=`User question:\n${question}\n\nCandidate A (${modelName(results[0].model)}):\n${results[0].text}\n\nCandidate B (${modelName(results[1].model)}):\n${results[1].text}\n\nAct as an independent reviewer. Return only the best final answer. Reconcile disagreements, remove unsupported claims, correct mistakes, and keep it concise unless detail is necessary.`;const rr=await puter.ai.chat([{role:'user',content:synthesis}],{model:reviewModel.id,normalize:true});const finalText=rr?.message?.content;if(!finalText)throw new Error('Reviewer returned no answer');await wait(180);star('reviewer','you');active=new Set(['you']);activeEdges=new Set(['reviewer:you']);answered=true;render();$('tick').textContent='✓';$('tick').classList.remove('bad');$('badge').textContent='VALIDATED';$('meta').textContent=`${kind.toUpperCase()} · ${modelName(reviewModel)}`;$('body').textContent=String(finalText).trim();$('agents').textContent=`Specialists: ${results.map(r=>modelName(r.model)).join(' + ')} · Reviewer: ${modelName(reviewModel)} · Live catalog: ${models.length} models`;answer.classList.add('open');workspace.classList.add('open');document.title='✓ AI Team answered';setTimeout(()=>document.title='AI Team',2600)}catch(e){answered=false;active=new Set(['you']);activeEdges.clear();render();$('tick').textContent='!';$('tick').classList.add('bad');$('badge').textContent='RETRY';$('meta').textContent='AI NETWORK';$('body').textContent=e?.msg||e?.message||String(e);$('agents').textContent='No result was marked validated.';answer.classList.add('open');workspace.classList.add('open');document.querySelector('.state').className='state error';$('stateText').textContent='RETRY'}finally{busy=false;render()}}
q.addEventListener('input',render);q.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}});go.addEventListener('click',ask);draw();
